[package]
name = "crust"
version = "0.1.0"
authors = ["onehrxn <waharaxn@gmail.com>"]
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1.11"
log = "0.4"
simple_logger = "5"

[features]
debug = []
ast = []
source = []
token = []
as = []

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench_lexer"
harness = false
[[bench]]
name = "bench_cpp"
harness = false
[[bench]]
name = "bench_parser"
harness = false
